"""
iepipeline02
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="hello_world")
def hello_world_func():
    print("Hello World")

default_args={
    "owner": "irfan.elahi@databricks.com,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-18", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "irfan.elahi@databricks.com": "mailto:irfan.elahi@databricks.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm79rovxt0q0401mltxg941g8/cloud-ide/cm79sgxab0q5m01ml52oitkux/cm79skv5a0q6k01mlmdd0u2ml",
    },
)
def iepipeline02():
    hello_world = hello_world_func()

dag_obj = iepipeline02()
